version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 9000:5000
    volumes:
      - .:/root/project
  mysql:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allographer
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      TZ: Asia/Tokyo
  postgres:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: allographer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      TZ: Asia/Tokyo
